# Generated by Django 6.0.7 on 2026-07-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plasticrate',
            options={},
        ),
        migrations.RemoveField(
            model_name='kioskuser',
            name='total_kg',
        ),
        migrations.RemoveField(
            model_name='plasticrate',
            name='points',
        ),
        migrations.RemoveField(
            model_name='plasticrate',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='kioskuser',
            name='total_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plasticrate',
            name='points_per_bottle',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
