# Generated by Django 6.0.7 on 2026-07-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_plasticrate_options_remove_kioskuser_total_kg_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlasticRate',
            new_name='BottleRate',
        ),
    ]
