# Generated by Django 6.0.5 on 2026-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_rename_plasticrate_bottlerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
