# Generated by Django 6.0.5 on 2026-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_transaction_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='condition',
            field=models.CharField(blank=True, choices=[('clean', 'Clean'), ('dirty', 'Dirty')], max_length=10, null=True),
        ),
    ]
