# Generated by Django 6.0.7 on 2026-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_transaction_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlerate',
            name='points_per_bottle',
            field=models.IntegerField(default=3),
        ),
    ]
