# Generated by Django 6.0.7 on 2026-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_alter_bottlerate_points_per_bottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='main-bin', max_length=64, unique=True)),
                ('is_full', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bin statuses',
            },
        ),
    ]
