# Generated by Django 6.0.7 on 2026-08-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_binstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=12)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_scans', to='kiosk.kioskuser')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='bscan_status_exp_idx')],
            },
        ),
    ]
